### PR TITLE
Added a new sub-menu for the Network Monitor section of DevTools docs.

### PR DESCRIPTION
**Pull request by irenesmith**
Added a new sub-menu to the Network Monitor section of the sidebar to provide access to the new pages created when I broke up the extremely long original page.

### CODE REVIEW

**Comment by irenesmith** [comment]
I think I properly addressed your comments. Thanks!

**Comment by irenesmith** [comment]
> I've had more thoughts about this. You should remove the slashes from the property/field names, so for example instead of "Network_Monitor/Toolbar", make it "Network_Monitor_Toolbar", or even "Toolbar" (provided this doesn't cause a naming conflict)
> 
> Also, in your list items you are using the property/field values, not the property/field names, so for example currently
> 
> `<li><a href="<=%=baseURL%>Network_Monitor/Throttling"><%=text["Throttling"]%></li>`
> 
> should be
> 
> `<li><a href="<=%=baseURL%>Network_Monitor/Throttling"><%=text["Network_Monitor/Throttling"]%></li>`

I think I have not addressed your requested changes.

**Comment by irenesmith** [comment]
Why has this not been merged? I updated the PR according to the last comments from @chrisdavidmills so I don't understand why it is still sitting here.

**Comment by chrisdavidmills** [comment]
I don't think you did this one:

> I've had more thoughts about this. You should remove the slashes from the property/field names, so for example instead of "Network_Monitor/Toolbar", make it "Network_Monitor_Toolbar", or even "Toolbar" (provided this doesn't cause a naming conflict)

**Comment by irenesmith** [comment]
> 
> 
> I don't think you did this one:
> 
> > I've had more thoughts about this. You should remove the slashes from the property/field names, so for example instead of "Network_Monitor/Toolbar", make it "Network_Monitor_Toolbar", or even "Toolbar" (provided this doesn't cause a naming conflict)

I've made those changes as well.

**Comment by chrisdavidmills** [comment]
> I've made those changes as well.

Ooh, one more thing; you still need to correct the JSON member names in the actual menu list structure. For example <%=text["Network_Monitor/Toolbar"]%> should be <%=text["Network_Monitor_Toolbar"]%>

**Comment by irenesmith** [comment]
@chrisdavidmills I've made all of the changes you requested. What is the remaining problem?

**Comment by chrisdavidmills** [comment]
@irenesmith It wasn't just missing underscores — there are also some words that need removing. Have another look at my last comment.

**Pull request merged**
