### PR TITLE
Bug 1491509: Fix {{CSSSyntax}} when an @‑rule is not found in DB

### PR DESCRIPTION
**Pull request by ExE-Boss**
Fixes [bug 1491509](https://bugzilla.mozilla.org/show_bug.cgi?id=1491509)

See [the `viewport‑fit` `@viewport` descriptor page](https://developer.mozilla.org/docs/Web/CSS/@viewport/viewport-fit) for a demonstration of the issue.

This was missed in #671 and #687 🤦🏻‍♂️

---

review?(@davidflanagan, @Elchi3, @jwhitlock, @wbamberg)

See also https://github.com/mdn/data/pull/283

### CODE REVIEW

**Comment by ExE-Boss** [comment]
review?(@jwhitlock): This is now **P1**

**Comment by jwhitlock** [comment]
Quick questions:

1. Why did you change the name of the macro?
2. Can you add tests?

**Comment by ExE-Boss** [comment]
1. Because I prefer proper capitalisation and KumaScript macro names are case insensitive (with the exception of `TemplateLink` calls, but that might be correctable), also `git blame` still works.
2. I’ll look into that.

**Comment by ExE-Boss** [comment]
@jwhitlock: This is now ready for a second round of review.

**Comment by ExE-Boss** [comment]
/ping @jwhitlock Can you please restart the&nbsp;build by&nbsp;pressing the&nbsp;**Restart&nbsp;build** button on&nbsp;[the&nbsp;Travis&nbsp;page](https://travis-ci.org/mdn/kumascript/builds/444467920)?

**Comment by ExE-Boss** [comment]
review?(@davidflanagan, @Elchi3, @jwhitlock, @wbamberg): Let’s&nbsp;get&nbsp;this&nbsp;merged.

**Comment by Elchi3** [comment]
Unsubscribing. I'm not reviewing this right now.

**Comment by jwhitlock** [comment]
This looks good, but I still need to think if the name change is acceptable.

**Comment by duduindo** [comment]
Guys, there are errors yet: 
* https://developer.mozilla.org/en-US/docs/Web/CSS/@viewport/viewport-fit

**Pull request closed without merging**
