### PR TITLE
Remove sundry internals macros

### PR DESCRIPTION
**Pull request by wbamberg**
I've rendered out the calls to these macros, which are all internal Mozilla docs.

## MakeSimpleQuicklinks.ejs

* Calls from Wiki pages: https://wiki.developer.mozilla.org/en-US/search?locale=*&kumascript_macros=MakeSimpleQuicklinks&topic=none

* Calls from other macros: https://github.com/mdn/kumascript/search?q=MakeSimpleQuicklinks&unscoped_q=MakeSimpleQuicklinks

## Toolkit_API_Official_References.ejs

* Calls from Wiki pages: https://wiki.developer.mozilla.org/en-US/search?locale=*&kumascript_macros=Toolkit_API_Official_References&topic=none

* Calls from other macros: https://github.com/mdn/kumascript/search?q=Toolkit_API_Official_References&unscoped_q=Toolkit_API_Official_References

## XULMeth2.ejs

* Calls from Wiki pages: https://wiki.developer.mozilla.org/en-US/search?locale=*&kumascript_macros=XULMeth2&topic=none

* Calls from other macros: https://github.com/mdn/kumascript/search?q=XULMeth2&unscoped_q=XULMeth2

## XULProp.ejs

* Calls from Wiki pages: https://wiki.developer.mozilla.org/en-US/search?locale=*&kumascript_macros=XULProp&topic=none

* Calls from other macros: https://github.com/mdn/kumascript/search?q=XULProp&unscoped_q=XULProp

## interface-method.ejs

* Calls from Wiki pages: https://wiki.developer.mozilla.org/en-US/search?locale=*&kumascript_macros=interface-method&topic=none

* Calls from other macros: https://github.com/mdn/kumascript/search?q=interface-method&unscoped_q=interface-method

## jsapi_maxversion_inline.ejs

* Calls from Wiki pages: https://wiki.developer.mozilla.org/en-US/search?locale=*&kumascript_macros=jsapi_maxversion_inline&topic=none

* Calls from other macros: https://github.com/mdn/kumascript/search?q=jsapi_maxversion_inline&unscoped_q=jsapi_maxversion_inline

## jsapi_provides_request.ejs

* Calls from Wiki pages: https://wiki.developer.mozilla.org/en-US/search?locale=*&kumascript_macros=jsapi_provides_request&topic=none

* Calls from other macros: https://github.com/mdn/kumascript/search?q=jsapi_provides_request&unscoped_q=jsapi_provides_request

## jsctypesxref.ejs

* Calls from Wiki pages: https://wiki.developer.mozilla.org/en-US/search?locale=*&kumascript_macros=jsctypesxref&topic=none

* Calls from other macros: https://github.com/mdn/kumascript/search?q=jsctypesxref&unscoped_q=jsctypesxref

## npapi.ejs

* Calls from Wiki pages: https://wiki.developer.mozilla.org/en-US/search?locale=*&kumascript_macros=npapi&topic=none

* Calls from other macros: https://github.com/mdn/kumascript/search?q=npapi&unscoped_q=npapi

## tb_minversion_inline.ejs

* Calls from Wiki pages: https://wiki.developer.mozilla.org/en-US/search?locale=*&kumascript_macros=tb_minversion_inline&topic=none

* Calls from other macros: https://github.com/mdn/kumascript/search?q=tb_minversion_inline&unscoped_q=tb_minversion_inline

## tbsource.ejs

* Calls from Wiki pages: https://wiki.developer.mozilla.org/en-US/search?locale=*&kumascript_macros=tbsource&topic=none

* Calls from other macros: https://github.com/mdn/kumascript/search?q=tbsource&unscoped_q=tbsource

### CODE REVIEW

**Comment by peterbe** [comment]
Pardon my ignorance but what's going to happen to places like my `localhost:8000` or `developer.allizom.org` where documents still use these macros?

**Comment by escattone** [comment]
> Pardon my ignorance but what's going to happen to places like my `localhost:8000` or `developer.allizom.org` where documents still use these macros?

Good question! For local development, we're long overdue for an updated sample database. I don't think we've created a new one for almost a year now. For `developer.allizom.org`, we'll need to update the DB using the latest from prod. I'll open issues for both of those.

**Comment by escattone** [comment]
FYI, I've created:
- https://github.com/mdn/infra/issues/353
- https://github.com/mdn/kuma/issues/6148

**Comment by wbamberg** [comment]
Thanks @escattone !

> Pardon my ignorance but what's going to happen to places like my localhost:8000 or developer.allizom.org where documents still use these macros?

Some pages will be broken until a new DB is made. Realistically I don't think the broken pages will be a problem for anyone: it's only a few pages, in very obsolete content. But if there's a use case I am missing here then I'd be happy to know about that.

**Pull request merged**
