### PR TITLE
removing web audio api guides to stop repetition in sidebar, also add…

### PR DESCRIPTION
**Pull request by chrisdavidmills**
…ing missing interfaces

To support update work Ruth John is doing on WAA.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Yes — if you look at the generated sidebar (see https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API), you'll see that many of the entries are duplicated. It seems like they are being created twice, and I thought getting rid of them out of here would get rid of one set, hopefully making it look a bit less messy.

**Comment by chrisdavidmills** [comment]
From a conversation with Florian:

> The deal here is that there's magic sidebar logic implemented, this time it's that some sidebars are designed so that Guide pages that are under the API overview page appear automatically in the guide list.
So for Web_Audio_API, all pages under https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API appear automatically as guides already and you don't need to add them separately to the JSON. When you do, they appear twice.

So I think I am right to remove these; otherwise they will be duplicated.

@Elchi3 , can you review this and merge it if you agree?

**Comment by chrisdavidmills** [comment]
I am not sure what is causing the Travis fail; my changes look OK.

**Comment by Elchi3** [comment]
Restarted travis, lgtm otherwise

**Comment by chrisdavidmills** [comment]
Cool, thanks! In that case can you approve and merge?

**Comment by chrisdavidmills** [comment]
Yay, thanks!

**Pull request merged**
