### PR TITLE
Remove event properties macros

### PR DESCRIPTION
**Pull request by Elchi3**
:skull: :skull: :skull: 

This deletes 32 macros in the event reference that were used to create event property tables.
This was a nightmare, because it basically blocked maintaining good property lists and made localization impossible. I have replaced the macro calls with real tables now, allowing everyone to edit this information directly in the wiki.

### CODE REVIEW

**Comment by Elchi3** [comment]
Thanks Will! 
I only see https://developer.mozilla.org/en-US/docs/Web/Events showing up as a false positive.
I think this is either due to https://bugzilla.mozilla.org/show_bug.cgi?id=1373848 or https://bugzilla.mozilla.org/show_bug.cgi?id=1213733

**Comment by jwhitlock** [comment]
Notice that this one ends in a slash:

screenshot 2017-12-22 11 13 04

The page is https://developer.mozilla.org/en-US/docs/Web/Events/ , which is distinct in the database from https://developer.mozilla.org/en-US/docs/Web/Events. However, other parts of Kuma noticed the slash and removes it, leaving the Events page.

I've manually changed the page to https://developer.mozilla.org/en-US/docs/Web/Events/onconnected%20(2). I'd appreciate if someone takes a look and decides where it should live and if it should be deleted.

I'll add a new test to [bug 1311142](https://bugzilla.mozilla.org/show_bug.cgi?id=1311142).

**Comment by Elchi3** [comment]
Oh excellent find @jwhitlock! I deleted the page, it is no longer relevant.

**Comment by jwhitlock** [comment]
There were 8 pages with trailing slashes. 6 were redirects (including one created when I changed the slug for ``onconnected``).  I fixed the two remaining ones:

* https://developer.mozilla.org/fr/docs/EXSLT/math/min - There's now a rendering error on this very old page.
* https://developer.mozilla.org/en-US/docs/User:lmorchard/ - The content was "This is a garbage page. Here is an edit.", so I deleted it.

**Comment by escattone** [comment]
Wow, great work @Elchi3, @wbamberg, and @jwhitlock !

**Pull request merged**
