### PR TITLE
update the README to indicate archival

### PR DESCRIPTION
**Pull request by escattone**
Update README to indicate that this repository will be archived.

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
The warning notice looks good, thanks @escattone .

I did wonder though — is the content below it even relevant anymore, and if so, should it be put inside a README in the next location and deleted from here?

**Comment by escattone** [comment]
@chrisdavidmills 

> I did wonder though — is the content below it even relevant anymore, and if so, should it be put inside a README in the next location and deleted from here?

No, it's not relevant anymore at all.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills
> 
> > I did wonder though — is the content below it even relevant anymore, and if so, should it be put inside a README in the next location and deleted from here?
> 
> No, it's not relevant anymore at all.

Maybe get rid of it then?

**Comment by escattone** [comment]
> > @chrisdavidmills
> > > I did wonder though — is the content below it even relevant anymore, and if so, should it be put inside a README in the next location and deleted from here?
> > 
> > 
> > No, it's not relevant anymore at all.
> 
> Maybe get rid of it then?

Good point, will do!

**Pull request merged**
