### PR TITLE
adding imsc specs to kumascript

### PR DESCRIPTION
**Pull request by chrisdavidmills**

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Darnit, sorry @a2sheppy it's still moaning about needing an approving review. @jwhitlock can you give this the necessary approval so it can be merged?

**Comment by tairt** [comment]
@a2sheppy It would be great if you review it. We want to present the MDN project on documenting IMSC on Monday. If it is not possible yet, I prefer to hardcode the reference of the specs on the MDN/IMSC landing page. Thanks  : )

**Comment by tairt** [comment]
Thanks @chrisdavidmills

**Comment by tairt** [comment]
Thanks @Elchi3

**Comment by a2sheppy** [comment]
Yeah, I don’t have merge privileges for some reason. I can’t even request reviews. I don’t know why.


--
Eric Shepherd
Senior Technical Writer
MDN Web Docs
https://developer.mozilla.org/

**Pull request merged**
