### PR TITLE
adding web socket inspector page to tools sidebar

### PR DESCRIPTION
**Pull request by chrisdavidmills**
I added a guide to the new web socket inspector:

https://wiki.developer.mozilla.org/en-US/docs/Tools/Network_Monitor/Inspecting_web_sockets

I wanted it to appear in the devtools sidebar

Relevant bug

https://bugzilla.mozilla.org/show_bug.cgi?id=1573805

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@wbamberg can you review this one for me please?

**Comment by wbamberg** [comment]
I'm not able to review this today because I've not been able to get my local Kuma working, again :(.

I can say that it looks OK, however note that https://github.com/mdn/kumascript/pull/1257 still isn't merged, and I'd like to see this comment: https://github.com/mdn/kumascript/pull/1257#issuecomment-545034385 addressed. If you like I can finish off https://github.com/mdn/kumascript/pull/1257 after this is merged?

**Comment by chrisdavidmills** [comment]
@wbamberg I've read the comment you cited, and d'you know what? I think I'd just prefer a link to the main Network Monitor page. You are right that it looks inconsistent. So can you finish off #1257, and I'll just close this one?

**Comment by wbamberg** [comment]
@chrisdavidmills , yeah, sounds good to me!

**Pull request closed without merging**
