### PR TITLE
fix: Resolve critical severity `npm audit` vulnerabilities

### PR DESCRIPTION
**Pull request by ExE-Boss**
review?(@a2sheppy, @davidflanagan, @Elchi3, @peterbe, @wbamberg)

---

I also kind‑of forgot about updating `jest` as a result of my old PC dying.

I’ll do that as soon as this is merged.

### CODE REVIEW

**Comment by peterbe** [comment]
Can you share what commands you ran to make this upgrade? `npm audit fix` (or whatever it's called, only fixes the shrinkwrap right?)

Also, can we just get rid of shrinkwrap and switch to the builtin `package-lock.json`?

**Comment by ExE-Boss** [comment]
`npm audit --fix` and `npm update`

**Comment by peterbe** [comment]
Is there no way to make these changes smaller?

**Comment by ExE-Boss** [comment]
I can split it into two commits like in #1127, which I probably should’ve done from the get‑go.

**Comment by peterbe** [comment]
> I can split it into two commits like in #1127, which I probably should’ve done from the get‑go.

That would be much appreciated! The smaller the atoms the better. 

Here's the review effect of few vs too many changes: 
source

**Comment by ExE-Boss** [comment]
Moved to #1226 and #1227.

**Pull request closed without merging**
