### PR TITLE
Update DefaultAPISidebar to list only guides from GroupData

### PR DESCRIPTION
**Pull request by wbamberg**
This PR updates the DefaultAPISidebar.ejs macro to list only guides that are explicitly listed in GroupData.json.

Currently,  DefaultAPISidebar.ejs will list guides in GroupData.json *and* subpages of the main overview page. If a subpage is also listed in GroupData.json, then the guide appears twice in the sidebar. For example:

Screen Shot 2019-05-23 at 4 11 17 PM

(https://developer.mozilla.org/en-US/docs/Web/API/WebVR_API).

This change was previously discussed in https://discourse.mozilla.org/t/defaultapisidebar-apiref-and-groupdata/40210/, in particular https://discourse.mozilla.org/t/defaultapisidebar-apiref-and-groupdata/40210/7.

Note that @a2sheppy doesn't like this approach because it means subpages are not automatically included and people have to add guides explicitly to GroupData. However:

1) I don't know of a practical alternative that can reliably fix this problem of guides appearing in the sidebar twice. Even if there are any, they would be more complicated. 
2) Lists of guides should generally be given in a specific order (i.e. starting with the basics, then moving on the advanced cases) which listing subpages can't provide.
3) Guides aren't written often enough for this to be a major problem in practice.
4) Many existing sidebars, such as [LearnSidebar.ejs](https://github.com/mdn/kumascript/blob/master/macros/LearnSidebar.ejs), also use an "explicit" approach, and it seems to work well enough there.

The change is a little intricate because the old code didn't handle localizations for pages listed in GroupData - so if there was a French translation of a guide, you'd still see the English title (it did handle localizations for subpages). This PR also fixes that.

This PR is not ready yet because I also need to update GroupData.json to include all the guides that are currently only given as subpages of the overview pages.

### CODE REVIEW

**Comment by wbamberg** [comment]
This is now ready for review.

I've updated GroupData. The basic idea of these updates is to find subpages of the API overview pages, and list them explicitly as guide pages, also ordering them sensibly (so for example "intro" guides come first, with more niche/advanced guides coming later).

I started with this page: https://developer.mozilla.org/en-US/docs/User:wbamberg/all-guide-pages which I believe lists subpages for every overview page for every group listed in GroupData. I looked at these subpages and if I thought they made sense as guides ([they don't always](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB_in_chrome)) added them into GroupData in the "guides" property, trying to order them sensibly. For example, many APIs have a "Using the Foo API" guide, and I generally put that first.

I also updated the sidebar code to just skip guides that didn't exist.

*****

Testing this is a bit involved. I did this:

1. set up a local Kuma
2. migrate all the API overview pages, with subpages, for all groups I changed:
```
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Beacon_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Frame_Timing_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Media_Capabilities_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Navigation_timing_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Performance_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Performance_Timeline  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Push_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Screen_Orientation_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Streams_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Touch_Events  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Websockets_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API  --depth 10
docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Web/API/WebVR_API  --depth 10
```
3. run `docker-compose restart`
4. visit every one of those overview pages and see if the sidebar is what we expect, given the content of GroupData:

* http://localhost:8000/en-US/docs/Web/API/Beacon_API
* http://localhost:8000/en-US/docs/Web/API/Canvas_API
* http://localhost:8000/en-US/docs/Web/API/Channel_Messaging_API
* http://localhost:8000/en-US/docs/Web/API/CSS_Object_Model
* http://localhost:8000/en-US/docs/Web/API/Document_Object_Model
* http://localhost:8000/en-US/docs/Web/API/Fetch_API
* http://localhost:8000/en-US/docs/Web/API/File_and_Directory_Entries_API
* http://localhost:8000/en-US/docs/Web/API/Fullscreen_API
* http://localhost:8000/en-US/docs/Web/API/Frame_Timing_API
* http://localhost:8000/en-US/docs/Web/API/Gamepad_API
* http://localhost:8000/en-US/docs/Web/API/Geolocation_API
* http://localhost:8000/en-US/docs/Web/API/HTML_Drag_and_Drop_API
* http://localhost:8000/en-US/docs/Web/API/IndexedDB_API
* http://localhost:8000/en-US/docs/Web/API/Media_Capabilities_API
* http://localhost:8000/en-US/docs/Web/API/Media_Streams_API
* http://localhost:8000/en-US/docs/Web/API/MediaStream_Recording_API
* http://localhost:8000/en-US/docs/Web/API/Navigation_timing_API
* http://localhost:8000/en-US/docs/Web/API/Payment_Request_API
* http://localhost:8000/en-US/docs/Web/API/Performance_API
* http://localhost:8000/en-US/docs/Web/API/Performance_Timeline
* http://localhost:8000/en-US/docs/Web/API/Permissions_API
* http://localhost:8000/en-US/docs/Web/API/Pointer_events
* http://localhost:8000/en-US/docs/Web/API/Push_API
* http://localhost:8000/en-US/docs/Web/API/Resource_Timing_API
* http://localhost:8000/en-US/docs/Web/API/Screen_Capture_API
* http://localhost:8000/en-US/docs/Web/API/Screen_Orientation_API
* http://localhost:8000/en-US/docs/Web/API/Server-Sent_Events
* http://localhost:8000/en-US/docs/Web/API/Service_Worker_API
* http://localhost:8000/en-US/docs/Web/API/Streams_API
* http://localhost:8000/en-US/docs/Web/API/Touch_Events
* http://localhost:8000/en-US/docs/Web/API/Web_Animations_API
* http://localhost:8000/en-US/docs/Web/API/Web_Audio_API
* http://localhost:8000/en-US/docs/Web/API/Web_Authentication_API
* http://localhost:8000/en-US/docs/Web/API/WebGL_API
* http://localhost:8000/en-US/docs/Web/API/Notifications_API
* http://localhost:8000/en-US/docs/Web/API/WebRTC_API
* http://localhost:8000/en-US/docs/Web/API/Websockets_API
* http://localhost:8000/en-US/docs/Web/API/Web_Storage_API
* http://localhost:8000/en-US/docs/Web/API/Web_Workers_API
* http://localhost:8000/en-US/docs/Web/API/WebVR_API

There are a few special cases:

* Canvas API, Service Worker API, WebGL API, WebRTC API all use their own custom sidebar macros, so won't be affected by this change
* for Geolocation API it might look odd that I removed the "Using Geolocation" guide, but that's because it's actually just a redirect to the overview page ([try it](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API))
* for Performance API it might look odd that not all the expected guides are listed: this is because the sidebar macro on this page is called like `{{DefaultAPISidebar("High Resolution Time")}}` not `{{DefaultAPISidebar("Performance API")}}` (https://developer.mozilla.org/en-US/docs/Web/API/Performance_API$edit). I don't know if this is intentional.

**Comment by wbamberg** [comment]
Thanks @chrisdavidmills for the review.

I think you know this but for the record: the main alternative I can see is: abolish the "guides" property and just use subpages. The advantages of this:

1. subpages get included automatically (no need to update GroupData)
2. less stuff in GroupData, so things are a bit simpler

Disadvantages:

1. you can't include guides from elsewhere (I think in practice this is a very minor limitation: as you can see, very few APIs want to do this)
2. you can't curate the order of links, they are always presented alphabetically. I think personally this is a significant drawback, but I'm a bit on the fence about whether it outweighs the advantages.

> Gamepad API:
>
> https://developer.mozilla.org/en-US/docs/Games/Techniques/Controls_Gamepad_API
This guide exists and is linked to in the current version of the landing page on MDN, but it didn't appear when testing your updated code

I knew I'd forgotten one! That's because it isn't a subpage of Gampepad_API so didn't get migrated.  Try: 

    docker exec kuma_worker_1 python ./manage.py scrape_document https://developer.mozilla.org/en-US/docs/Games/Techniques/Controls_Gamepad_API

...and shift-refresh, it ought to show up.

> Push API:
>
> The guide listed in this sidebar has the correct title ("Web Push API Notifications Best Practices") and URL, but the title listed in GroupData is "Push notifications best practices". A bit strange, so I thought I'd mention it in case it was significant.

That's because it is fetching the real page title using `wiki.getPage()`, and displaying that, and actually ignoring the "title" property. It needs to do this so it works properly in other locales, or it will just display the (English) version from "title".

For an example of the current behavior, see https://developer.mozilla.org/en-US/docs/Web/API/WebVR_API. In this case guides are listed in "guides" and they are also subpages, so they are listed twice. In the French version: https://developer.mozilla.org/fr/docs/Web/API/WebVR_API, the links taken from subpages (the first three) use the French translation of the title, while the links taken from "guides" use the English text from "guides.title".

I'm pretty sure we ought to remove "title" from "guides", and just have the URL, and will do that in a follow-up. I didn't do it in this PR because wanted to keep this change as small as possible, but perhaps I should do it in this PR after all?

**Comment by chrisdavidmills** [comment]
> you can't curate the order of links, they are always presented alphabetically. I think personally this is a significant drawback, but I'm a bit on the fence about whether it outweighs the advantages.

I think this is a significant enough drawback that the approach you've chosen wins out. And in terms of it not updating automatically...well, it's not as if we find ourselves wanting to add new guides to API sidebars every day anyhow.

> ...and shift-refresh, it ought to show up.

Yup, the 2nd Gamepad guide now shows up. Perfect. Thinkig about what you said earlier, I think the ability to include guides not under the API landing page in the tree is good for flexibility. We don't use this often, but we want this.

> That's because it is fetching the real page title using wiki.getPage(), and displaying that, and actually ignoring the "title" property. It needs to do this so it works properly in other locales, or it will just display the (English) version from "title".

Ah right, ok, now I get it.

> I'm pretty sure we ought to remove "title" from "guides", and just have the URL, and will do that in a follow-up. I didn't do it in this PR because wanted to keep this change as small as possible, but perhaps I should do it in this PR after all?

Yeah, we need this eventually. But I'd do this in a separate PR; keep things as simple as possible.

**Comment by wbamberg** [comment]
OK, let's merge this terrifying thing.

**Pull request merged**
