### PR TITLE
chore(package): Update Jest to version 24.9

### PR DESCRIPTION
**Pull request by ExE-Boss**
Just like I promised in #1224.

Depends on: #1057, as I wasn’t able to verify if the update worked otherwise.

### CODE REVIEW

**Comment by peterbe** [comment]
Now, this PR is mixing two different things. One is a jest upgrade, the other is a fix for the tests under windows. **Why can't this be two distinct PRs?**

**Comment by ExE-Boss** [comment]
So, can you merge #1057 first, so that I can verify whether the update work correctly?

(it’s SemVer‑breaking, so I need to test it locally)

**Comment by peterbe** [comment]
@ExE-Boss I got emails that seem to indicate that you made different git commits. But it certainly appears that you have squashed and rebased it down to 1 commit. If you need to do that, close the PR first otherwise we can't see what changed and it makes reviewing frustrating. Please. If you need to rebase because `master` has "changed under your feet" just rebase without changing any of the commits.

**Comment by ExE-Boss** [comment]
I only removed the commits that were merged into master (i.e. #1057)

**Pull request closed without merging**
