### PR TITLE
Remove ArticlesByTag macro

### PR DESCRIPTION
**Pull request by a2sheppy**
Fixed the escaping of the text here, and added code to remove
 tags from the summaries. This fixes some more cases of
HTML tags in text being rendered instead of just printed in
plaintext, and avoids  tags showing up in tooltips as raw
HTML when this macro is used.

### CODE REVIEW

**Comment by Elchi3** [comment]
I can't any usages of this macro on MDN.
https://developer.mozilla.org/en-US/search?locale=en-US&kumascript_macros=ArticlesByTag&topic=none Gives me a false positive and it doesn't seem that other macros are using this.

Can you elaborate which issues on which pages are fixed here exactly?

**Comment by a2sheppy** [comment]
It’s possible then that this is a macro that I created but could not use
due to some of the issues that existed and should now be fixed in the other
macros I updated this week. That said, if it isn’t in use at this time, we
could probably just remove this macro (although it still seems potentially
useful).

I fixed it only because I was making a pass at improving a set of related
macros and this was in that set.

Eric Shepherd
Senior Technical Writer
MDN Web Docs: https://developer.mozilla.org/
Blog: http://www.bitstampede.com/
Twitter: http://twitter.com/sheppy

On Nov 3, 2017 at 9:40 AM, Florian Scholz <notifications@github.com> wrote:


I can't any usages of this macro on MDN.
https://developer.mozilla.org/en-US/search?locale=en-US&kumascript_macros=ArticlesByTag&topic=none
Gives me a false positive and it doesn't seem that other macros are using
this.

Can you elaborate which issues on which pages are fixed here exactly?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mdn/kumascript/pull/387#issuecomment-341705871>, or mute
the thread

**Comment by Elchi3** [comment]
> That said, if it isn’t in use at this time, we could probably just remove this macro (although it still seems potentially useful).

I would say let's remove it then. I see no point in maintaining/localizing/being responsible for unused code.

**Comment by a2sheppy** [comment]
That's weird. I updated this PR to remove the macro outright, but I don't see that change here now...

**Pull request merged**
