### PR TITLE
Streams api

### PR DESCRIPTION
**Pull request by chrisdavidmills**
Cleaning up the Streams API GroupData entry; with everything in the API added into the sidebar it was too busy and not that useful.

### CODE REVIEW

**Comment by Elchi3** [comment]
This cleanup was done in https://github.com/mdn/kumascript/pull/360, too.
Can you rebase, so that we still add these things?

```diff
+ "overview":   [ "Streams API" ],
+ "methods":    [ "WindowOrWorkerGlobalScope.fetch()" ],
+ "properties": [ "Body.body" ],
```

**Comment by chrisdavidmills** [comment]
Ummmm, did I do that correctly @Elchi3 ? Fingers crossed ;-)

**Comment by Elchi3** [comment]
Meeh, I squashed and merged https://github.com/mdn/kumascript/commit/cfc9dd5b5c5661840331ede5ec7307ccab2fb38b, but it seems like you didn't rebase against the latest master, so https://github.com/mdn/kumascript/pull/364  was reverted :/ I should have checked more carefully.

**Comment by chrisdavidmills** [comment]
Weird, I did fetch the latest upstream and rebase my master against it, then rebase this branch against that before pushing it. I wonder what I did wrong? I am really crap at rebasing.

**Comment by Elchi3** [comment]
I don't really know, but I should have checked better. Anyway, it's all good now :)

**Pull request merged**
