### PR TITLE
subpagesExpand fails for localized URLs

### PR DESCRIPTION
**Pull request by SphinxKnight**
A fix for #307. As I don't have my local env right now, I didn't test this one yet but this should be pretty straightforward.

The first commit I have in this PR was an "update my fork vs. master" commit and can be squashed without any problem.

### CODE REVIEW

**Comment by jwhitlock** [comment]
@SphinxKnight can you enable "Allow edits from maintainers" for this PR? - https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by SphinxKnight** [comment]
@jwhitlock it's actually checked on my side (I unchecked/checked would it have any side effect...)

**Comment by jwhitlock** [comment]
This isn't an AWS blocker, so I'm un-nominating myself for reviewer

**Comment by SphinxKnight** [comment]
Thanks for the time spent on it, I'll investigate during the upcoming week.

**Comment by SphinxKnight** [comment]
@Elchi3 I finally took the time to dig into this. I've tested this OK on my local instance but would appreciate a look :$.

N.B. I should have noted all the diacritics in https://developer.mozilla.org/fr/docs/with-errors before.

**Comment by Elchi3** [comment]
Thanks @SphinxKnight! 

This seems to be a regression of https://github.com/mdn/kumascript/pull/241. /cc @escattone 

Without tests, and no immediate re-render of pages, it takes a few months (in this case 2 months) until we discover things like this. :( 

To fix the root cause, I think we need to fix Dekiscript-Page.ejs

Line 53 (in the `subpages` function):
```diff
- var url = build_api_url((path ? path : env.url) + '$children');
+ var url = build_api_url((path ? encodeURI(path) : env.url) + '$children
```

Line 76 (in the `subpagesExpand` function):
```diff
- var url = build_api_url((path ? path : env.url) + '$children?expand');
+ var url = build_api_url((path ? encodeURI(path) : env.url) + '$children?expand');
```

Line 216 (in the `translations` function):
```diff
- var url = build_api_url((path ? path : env.url) + '$json');
+ var url = build_api_url((path ? encodeURI(path) : env.url) + '$json');
```

I looked at the tests, but I'm not 100% sure how to write a test for this case. Maybe Ryan could help here.

**Comment by Elchi3** [comment]
Closing this in favor of https://github.com/mdn/kumascript/pull/422

**Pull request closed without merging**
