### PR TITLE
Houdini

### PR DESCRIPTION
**Pull request by estelle**
@jpmedley Feel free to edit. I did what I thought made sense, but you might feel differently.

### CODE REVIEW

**Comment by jpmedley** [comment]
The data looks right. I can't go beyond that. After all this time (I'm sad to say), I'm still unclear on how this and interface tags interact to create side navigation.

**Review by chrisdavidmills — APPROVED** [review]
LGTM, r+

**Comment by estelle** [comment]
that only took 15 months!

**Comment by chrisdavidmills** [comment]
@estelle I've been busy, y'know? ;-)

**Pull request merged**
