### PR TITLE
fix: Resolve high severity `npm audit` vulnerabilities

### PR DESCRIPTION
**Pull request by ExE-Boss**
review?(@davidflanagan, @peterbe, @wbamberg)

### CODE REVIEW

**Comment by peterbe** [comment]
Is that from using `npm audit --fix`?

**Comment by davidflanagan** [comment]
Presumably this needs to have an update to package.json as well, doesn't it?

**Comment by ExE-Boss** [comment]
There were only updates to dependencies of dependencies.

**Comment by ExE-Boss** [comment]
Yes, I’ll&nbsp;do that after this is&nbsp;merged to&nbsp;avoid merge&nbsp;conflicts.

**Comment by ExE-Boss** [comment]
review?(@peterbe): Can this be merged now?

**Comment by peterbe** [comment]
First, can you check if anything's been changed in the package-lock.json since this was last CI tested?

**Comment by ExE-Boss** [comment]
The last change to `npm‑shrinkwrap.json` was on the **15<sup>th</sup> of February 2019**, which was two months before I opened this PR.

**TL;DR:** There were no changes to `npm‑shrinkwrap.json` since the last CI build.

**Comment by peterbe** [comment]
Yay! Let's tackle that `jest` dependency next.

**Pull request merged**
