### PR TITLE
Adding the distribution options page to the sidebar

### PR DESCRIPTION
**Pull request by irenesmith**
According to this [MDN Sprints Issue #546](https://app.zenhub.com/workspaces/mdn-sprint-board-5ab3d23fd0f4ea53b0022a61/issues/mdn/sprints/546), adding the Distribution Options page to the sidebar under Browser Extensions.

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Also, the Travis build check is failing; you need to look into why

**Comment by irenesmith** [comment]
Removed the line as you suggested.
This page is for browser extensions. Most of the other distribution pages will probably be removed as we reorganize the browser extensions. I decided to wait and remove the other pages as I finish reorganizing the extensions section as a whole. I have to swing the entire browser extensions section directly under Mozilla and re-work the add-ons pages and incorporate the information into browser extensions. A BIG task.

**Comment by chrisdavidmills** [comment]
OK, cool, thanks.

You've still got a failing Travis build; see the "Details" link in the "All checks have failed" section. The most useful line in there is "Unexpected token (80:5) in macros/AddonSidebar.ejs"

**Comment by caitmuenster** [comment]
@irenesmith, have you had a chance to revise this PR based on @chrisdavidmills' suggestion?

**Comment by chrisdavidmills** [comment]
@irenesmith please fix up this PR asap. You just need to add three commas, so it should be a really quick one.

Thanks!

**Pull request merged**
