### PR TITLE
Update tools sidebar

### PR DESCRIPTION
**Pull request by irenesmith**
According to [Sprints 2132](https://app.zenhub.com/workspaces/mdn-sprint-board-5ab3d23fd0f4ea53b0022a61/issues/mdn/sprints/2132) I am updating the tools sidebar to improve access to the Developer Tools documentation:
- Removed the "Core Tools" submenu
- Moved the core tools list to the top level of the menu
- Removed the duplicated link for the Accessibility Inspector from the More Tools list
- Removed references to the deprecated tools page
- Moved the link to the Tips page to the bottom of the menu

### CODE REVIEW

**Comment by irenesmith** [comment]
> 
> 
> I've tested this on my local KumaScript, and the menu looks fine, but there are a few slightly odd things about the hrefs of some of the menu items:
> 
> `Connecting to Firefox for Android`, `Connecting to iframes`, and `Connecting to other browsers` point to absolute URLs, whereas they should be pointing to relative URLs of the form <%=baseURL%> plus a modifier.
> 
> `Extending the devtools` is pointing to a relative URL, but an incorrect one.

It's weird that there are problems because I just moved things around. I'll correct the links and resubmit.

**Comment by wbamberg** [comment]
Sorry for the drive-by, but for this:

```html
    <li><a href="<%=baseURL%>Page_Inspector"><%=text['Page_Inspector']%></a></li>
    <li><a href="<%=baseURL%>Web_Console"><%=text['Web_Console']%></a></li>
    <li><a href="<%=baseURL%>Debugger"><%=text['JavaScript_Debugger']%></a></li>
    <li class="toggle">
      <details>
        <summary><%=text['Network_Monitor']%></summary>
        <ol>
            <li><a href="<%=baseURL%>Network_Monitor/Toolbar"><%=text['Network_monitor_toolbar']%></a></li>
            <li><a href="<%=baseURL%>Network_Monitor/request_list"><%=text['Network_monitor_request_list']%></a></li>
            <li><a href="<%=baseURL%>Network_Monitor/request_details"><%=text['Network_monitor_request_details']%></a></li>
            <li><a href="<%=baseURL%>Network_Monitor/recording"><%=text['Network_monitor_recording']%></a></li>
            <li><a href="<%=baseURL%>Network_Monitor/Performance_Analysis"><%=text['Network_monitor_performance_analysis']%></a></li>
            <li><a href="<%=baseURL%>Network_Monitor/Throttling"><%=text['Network_monitor_throttling']%></a></li>
        </ol>
      </details>
    </li>
    <li><a href="<%=baseURL%>Performance"><%=text['Performance']%></a></li>
    <li><a href="<%=baseURL%>Responsive_Design_Mode"><%=text['Responsive_Design_Mode']%></a></li>
    <li><a href="<%=baseURL%>Accessibility_inspector"><%=text['Accessibility_Inspector']%></a></li>
```

...I don't know why "Network Monitor" is placed in its own `summary`, with subpages, while the other tools just have an `li` with a link to the main page. This looks inconsistent, and also means I don't get a link to the main "Network Monitor" page. Why not instead:

```html
    <li><a href="<%=baseURL%>Page_Inspector"><%=text['Page_Inspector']%></a></li>
    <li><a href="<%=baseURL%>Web_Console"><%=text['Web_Console']%></a></li>
    <li><a href="<%=baseURL%>Debugger"><%=text['JavaScript_Debugger']%></a></li>
    <li><a href="<%=baseURL%>Network Monitor"><%=text['Network_Monitor']%></a></li>
    <li><a href="<%=baseURL%>Performance"><%=text['Performance']%></a></li>
    <li><a href="<%=baseURL%>Responsive_Design_Mode"><%=text['Responsive_Design_Mode']%></a></li>
    <li><a href="<%=baseURL%>Accessibility_inspector"><%=text['Accessibility_Inspector']%></a></li>
```

**Comment by chrisdavidmills** [comment]
@wbamberg, you said you'd sort this out, right? Just checking ;-)

**Comment by wbamberg** [comment]
> @wbamberg, you said you'd sort this out, right? Just checking ;-)

Yes :)

**Comment by wbamberg** [comment]
@chrisdavidmills , I've updated Irene's PR to remove the "Network Monitor" submenu, and the test code so it makes sense :).

**Comment by wbamberg** [comment]
I've also fixed those links, which should I hope address https://github.com/mdn/kumascript/pull/1257#pullrequestreview-304806304.

**Pull request merged**
