### PR TITLE
Add Screen Capture API (Q4S3)

### PR DESCRIPTION
**Pull request by a2sheppy**
Adds the Screen Capture API, which adds methods and
properties to interfaces from other specifications,
introduces two new data types, and one new guide page.

Part of the Chaka Khan sprint.

### CODE REVIEW

**Comment by a2sheppy** [comment]
I... what?

**Comment by a2sheppy** [comment]
That error is not related to the changes in this PR, so I don't know what to tell you. I don't know where that error is coming from.

**Comment by a2sheppy** [comment]
Oh, I bet `eventref` isn't properly hardened to handle cases where the `events` property is missing form the data object. I'll add an empty one.

**Comment by chrisdavidmills** [comment]
OK, that works! Cheers @a2sheppy !

**Pull request merged**
