### PR TITLE
Translate {{HTTPSidebar}} to Korean

### PR DESCRIPTION
**Pull request by cs09g**

### CODE REVIEW

**Comment by ExE-Boss** [comment]
The pull request name should be:
**feat: Translate {{HTTPSidebar}} to Korean**

**Comment by cs09g** [comment]
@ExE-Boss Where can I find the rule for commit or PR name? so I could follow.

**Comment by ExE-Boss** [comment]
I tend to use a modified [angular.js commit format](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines) (I capitalise the subject)

As for the subject itself, that should be a descriptive summary. For this, that would be: **“Translate {{HTTPSidebar}} to Korean”**.

**Comment by wbamberg** [comment]
Also, @cs09g :

> @ExE-Boss Where can I find the rule for commit or PR name? so I could follow.

The KumaScript repository doesn't have a policy for commit messages or PR names, so don't worry about this. It is a good idea for names to be clear of course, but there are no specific rules to follow here.

**Pull request merged**
